arrowParens: "avoid"
bracketSameLine: true
bracketSpacing: false
embeddedLanguageFormatting: "auto"
htmlWhitespaceSensitivity: "css"
insertPragma: false
jsxSingleQuote: false
printWidth: 120
proseWrap: "always"
quoteProps: "as-needed"
requirePragma: true
semi: true
singleQuote: true
tabWidth: 4
trailingComma: "es5"
useTabs: true
vueIndentScriptAndStyle: false
